### ISSUE TITLE
PowerShell cmdlets error on initial Database Migration creation

### ISSUE THREAD

**Issue by fmorriso** [chsakell/dotnetcore-entityframework-api#6]
The following PowerShell cmdlet, executed in the Package Manager Console of Visual Studio 2017 Enterprise (15.2.26430.14) with the `Default Project:` dropdown listbox set to `Scheduler.API` causes an error:

```powershell
Add-Migration -Name Initial -Project Scheduler.API
```
Startup project 'Scheduler.Model' targets framework '.NETStandard'. This framework is not intended for execution and may fail to resolve runtime dependencies. If so, select a different startup project and try again.
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.EntityFrameworkCore.Design, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Microsoft.EntityFrameworkCore.Design, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.EntityFrameworkCore.Tools.ReflectionOperationExecutor..ctor(String assembly, String startupAssembly, String projectDir, String contentRootPath, String dataDirectory, String rootNamespace, String environment)

I have updated all NuGet packages in all 3 projects to the latest editions (July 1, 2017).

**Comment by chsakell** [comment]
@fmorriso  simply try to cd to path of the _Scheduler.API_ project and run the following commands:

1. Add-Migration Initial
2. Update-Database

![add-migration](https://user-images.githubusercontent.com/7770797/27772432-4e70dc38-5f6b-11e7-82a5-da9978a03034.png)
